name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd my-react-app
        npm ci

    - name: Run ESLint
      run: |
        cd my-react-app
        npm run lint

    - name: Type check
      run: |
        cd my-react-app
        npm run build

    - name: Run tests (if exists)
      run: |
        cd my-react-app
        npm test --if-present

  deploy-preview:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        cd my-react-app
        npm ci

    - name: Build project
      run: |
        cd my-react-app
        npm run build

    - name: Deploy to preview
      run: echo "Deploy preview would go here"
